name: Sandbox dnscrypt-proxy workflow

on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 1 * * 6"
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install dnscrypt-proxy
        run: brew install dnscrypt-proxy

      - name: Copy sandbox file to /Users/runner
        run: cp dnscrypt-proxy.sb /Users/runner

      - name: Copy LauchDaemon plist to /Library/LaunchDaemons
        run: sudo cp goonnowgit.dnscrypt-proxy.plist /Library/LaunchDaemons

      - name: Just use cloudflare to make the start up process quick
        run: sed -i -e "s/^# server_names.*$/server_names = ['cloudflare']/" /usr/local/etc/dnscrypt-proxy.toml

      - name: Set application log
        run: sed -i -e "s/# log_file = 'dnscrypt-proxy.log'/log_file = '\/usr\/local\/etc\/dnscrypt-proxy.log'/" /usr/local/etc/dnscrypt-proxy.toml

      - name: Start dnscrypt-proxy
        run: sudo launchctl load -w /Library/LaunchDaemons/goonnowgit.dnscrypt-proxy.plist

      - name: Get status
        run: sudo launchctl list | grep dnscrypt-proxy

      - name: Give it a moment...
        run: while [[ -z $(grep "dnscrypt-proxy is ready" /usr/local/etc/dnscrypt-proxy.log) ]]; do sleep 1; done

      - name: Check log for a proper startup
        run: cat /usr/local/etc/dnscrypt-proxy.log

      - name: Do a DNS lookup
        run: dig @127.0.0.1 www.google.com

